# Generated by Django 4.1.7 on 2023-03-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='BookListAPI_price_779a55_idx',
        ),
    ]
